/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FirstLoginRouteImport } from './routes/first-login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCheckinsRouteImport } from './routes/_app/checkins'
import { Route as AppGoalsReviewRouteImport } from './routes/_app/goals_.review'
import { Route as AppCheckinsTeamRouteImport } from './routes/_app/checkins_.team'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminSharedGoalsRouteImport } from './routes/_app/admin/shared-goals'
import { Route as AppAdminCyclesRouteImport } from './routes/_app/admin/cycles'
import { Route as AppAdminCompletionRouteImport } from './routes/_app/admin/completion'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstLoginRoute = FirstLoginRouteImport.update({
  id: '/first-login',
  path: '/first-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinsRoute = AppCheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsReviewRoute = AppGoalsReviewRouteImport.update({
  id: '/goals_/review',
  path: '/goals/review',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinsTeamRoute = AppCheckinsTeamRouteImport.update({
  id: '/checkins_/team',
  path: '/checkins/team',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSharedGoalsRoute = AppAdminSharedGoalsRouteImport.update({
  id: '/admin/shared-goals',
  path: '/admin/shared-goals',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCyclesRoute = AppAdminCyclesRouteImport.update({
  id: '/admin/cycles',
  path: '/admin/cycles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCompletionRoute = AppAdminCompletionRouteImport.update({
  id: '/admin/completion',
  path: '/admin/completion',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/first-login': typeof FirstLoginRoute
  '/login': typeof LoginRoute
  '/checkins': typeof AppCheckinsRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/completion': typeof AppAdminCompletionRoute
  '/admin/cycles': typeof AppAdminCyclesRoute
  '/admin/shared-goals': typeof AppAdminSharedGoalsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/checkins/team': typeof AppCheckinsTeamRoute
  '/goals/review': typeof AppGoalsReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/first-login': typeof FirstLoginRoute
  '/login': typeof LoginRoute
  '/checkins': typeof AppCheckinsRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/completion': typeof AppAdminCompletionRoute
  '/admin/cycles': typeof AppAdminCyclesRoute
  '/admin/shared-goals': typeof AppAdminSharedGoalsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/checkins/team': typeof AppCheckinsTeamRoute
  '/goals/review': typeof AppGoalsReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/first-login': typeof FirstLoginRoute
  '/login': typeof LoginRoute
  '/_app/checkins': typeof AppCheckinsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/completion': typeof AppAdminCompletionRoute
  '/_app/admin/cycles': typeof AppAdminCyclesRoute
  '/_app/admin/shared-goals': typeof AppAdminSharedGoalsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/checkins_/team': typeof AppCheckinsTeamRoute
  '/_app/goals_/review': typeof AppGoalsReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/first-login'
    | '/login'
    | '/checkins'
    | '/dashboard'
    | '/goals'
    | '/profile'
    | '/reports'
    | '/admin/audit'
    | '/admin/completion'
    | '/admin/cycles'
    | '/admin/shared-goals'
    | '/admin/users'
    | '/checkins/team'
    | '/goals/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/first-login'
    | '/login'
    | '/checkins'
    | '/dashboard'
    | '/goals'
    | '/profile'
    | '/reports'
    | '/admin/audit'
    | '/admin/completion'
    | '/admin/cycles'
    | '/admin/shared-goals'
    | '/admin/users'
    | '/checkins/team'
    | '/goals/review'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/first-login'
    | '/login'
    | '/_app/checkins'
    | '/_app/dashboard'
    | '/_app/goals'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/admin/audit'
    | '/_app/admin/completion'
    | '/_app/admin/cycles'
    | '/_app/admin/shared-goals'
    | '/_app/admin/users'
    | '/_app/checkins_/team'
    | '/_app/goals_/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  FirstLoginRoute: typeof FirstLoginRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-login': {
      id: '/first-login'
      path: '/first-login'
      fullPath: '/first-login'
      preLoaderRoute: typeof FirstLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkins': {
      id: '/_app/checkins'
      path: '/checkins'
      fullPath: '/checkins'
      preLoaderRoute: typeof AppCheckinsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals_/review': {
      id: '/_app/goals_/review'
      path: '/goals/review'
      fullPath: '/goals/review'
      preLoaderRoute: typeof AppGoalsReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkins_/team': {
      id: '/_app/checkins_/team'
      path: '/checkins/team'
      fullPath: '/checkins/team'
      preLoaderRoute: typeof AppCheckinsTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/shared-goals': {
      id: '/_app/admin/shared-goals'
      path: '/admin/shared-goals'
      fullPath: '/admin/shared-goals'
      preLoaderRoute: typeof AppAdminSharedGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/cycles': {
      id: '/_app/admin/cycles'
      path: '/admin/cycles'
      fullPath: '/admin/cycles'
      preLoaderRoute: typeof AppAdminCyclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/completion': {
      id: '/_app/admin/completion'
      path: '/admin/completion'
      fullPath: '/admin/completion'
      preLoaderRoute: typeof AppAdminCompletionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCheckinsRoute: typeof AppCheckinsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminCompletionRoute: typeof AppAdminCompletionRoute
  AppAdminCyclesRoute: typeof AppAdminCyclesRoute
  AppAdminSharedGoalsRoute: typeof AppAdminSharedGoalsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppCheckinsTeamRoute: typeof AppCheckinsTeamRoute
  AppGoalsReviewRoute: typeof AppGoalsReviewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCheckinsRoute: AppCheckinsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminCompletionRoute: AppAdminCompletionRoute,
  AppAdminCyclesRoute: AppAdminCyclesRoute,
  AppAdminSharedGoalsRoute: AppAdminSharedGoalsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppCheckinsTeamRoute: AppCheckinsTeamRoute,
  AppGoalsReviewRoute: AppGoalsReviewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  FirstLoginRoute: FirstLoginRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
